### ISSUE TITLE
Upload local file to container?

### ISSUE THREAD

**Issue by aharth** [wintechis/solid-curl#2]
I would like to upload a index.html,  which is in my local file system, via solid-curl to an LDP container.

I have come as far as:
````
$ solid-curl https://solid.ti.rw.fau.de/public/2023/solid-symposium/ -X PUT -u sc
````

How can I specify I would like to upload the file index.html?

**Comment by dschraudner** [comment]
Analogous to the real cURL you can specify the data to send in the request using the `-d/--data` parameter. If an `@` follows then the file after the `@` will be read by `solid-curl` and sent in the request. All in all:
```
solid-curl https://solid.ti.rw.fau.de/public/2023/solid-symposium/ -X PUT -u sc -d @index.html
```

**Comment by aharth** [comment]
PUT to containers is not allowed, need to specify the full URI (including index.html):
````
solid-curl https://solid.ti.rw.fau.de/public/2023/solid-symposium/index.html -X PUT -u sc -d @index.html
````

**Comment by aharth** [comment]
And of course, one has to tell the Solid server that the content type is "text/html":

````
solid-curl https://solid.ti.rw.fau.de/public/2023/solid-symposium/index.html -X PUT -u sc -d @index.html --header "Content-Type: text/html"
````
